[package]
name = "carolus"
version = "0.1.0"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
serde = "1.0"
serde_derive = "1.0"
diesel = { version = "0.16.0", features = ["sqlite", "chrono"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
libsqlite3-sys = "*"
chrono = "*"
reqwest = "*"
url = "*"
serde_json = "1.0"
glob = "*"
blake2 = "0.6"
digest = { version = "0.6", features = ["std"]}
base64 = "0.7.0"
regex = "0.2"
log = "*"
failure = "*"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["json"]

[features]
tls = ["rocket/tls"]
sqlite-bundled = ["libsqlite3-sys/bundled"]
