[package]
name = "carolus"
version = "0.1.0"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
dotenv = "0.9.0"
iron = "*"
router = "*"
mount = { git = "https://github.com/iron/mount.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.5.1"

file_index  =  { path = "file-index" }
data = { path = "data" }
