[package]
name = "carolus"
version = "0.1.0"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
rocket = "0.3.11"
rocket_codegen = "0.3.11"
rocket_contrib = { version = "0.3.11", default-features = false, features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
diesel = { version = "1.3.0", features = ["sqlite", "chrono"] }
libsqlite3-sys = "*"
chrono = "*"
reqwest = "*"
url = "*"
serde_json = "1.0"
glob = "*"
blake2 = "0.6"
digest = { version = "0.6", features = ["std"]}
base64 = "0.7.0"
regex = "0.2"
log = "*"
failure = "*"

[features]
tls = ["rocket/tls"]
sqlite-bundled = ["libsqlite3-sys/bundled"]
