[package]
name = "file_index"
version = "0.1.0"
authors = ["simon"]

[dependencies]
glob = "*"
data = { path = "../data" }
blake2 = "0.6"
digest = { version = "0.6", features = ["std"]}
base64 = "0.7.0"
