[package]
name = "provider"
version = "0.1.0"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
reqwest = "*"
url = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
